apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-routing
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: argocd-routing
    repoURL: https://github.com/sam-delap/k8s-homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
